coverage:
  precision: 2
  round: down
  range: "50...90"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "coverage/**"
  - "docs/**"
  - "tests/e2e/**"
  - "**/*.d.ts"
